# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from PyQt5 import QtWebEngineWidgets



class Ui_PyDialog(object):
    def setupUi(self, PyDialog):
        PyDialog.setObjectName("PyDialog")
        PyDialog.resize(460, 264)
        PyDialog.setModal(True)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(PyDialog)
        self.webEngineView.setGeometry(QtCore.QRect(10, 20, 431, 201))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.buttonBox = QtWidgets.QDialogButtonBox(PyDialog)
        self.buttonBox.setGeometry(QtCore.QRect(270, 230, 166, 26))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(PyDialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 230, 251, 26))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(PyDialog)
        QtCore.QMetaObject.connectSlotsByName(PyDialog)

    def retranslateUi(self, PyDialog):
        _translate = QtCore.QCoreApplication.translate
        PyDialog.setWindowTitle(_translate("PyDialog", "PyDialog"))
